apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dito-demo-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jpsilva15/-Dito-Desafio-DevOps-III.git
    targetRevision: main
    path: manifests/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    # sync manual: aplique via `argocd app sync dito-demo-production` ou pela UI
