apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dito-demo-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jpsilva15/-Dito-Desafio-DevOps-III.git
    targetRevision: main
    path: manifests/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
